FirstWebApp/FirstWebApp/Controllers/ManufacturerController.cs
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.Collections.Generic;
using FirstWebApp.Models.IdentityModels;

namespace FirstWebApp.Controllers
{
    public class ManufacturerController : Controller
    {
        private ApplicationDbContext _context;

        public ManufacturerController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Manufacturers
        public ViewResult Index()
        {
            var manufacturers = _context.Manufacturers.Include(c => c.MembershipType).ToList();
            return View(manufacturers);
        }

        public ActionResult Details(int Id)
        {
            var manufacturer = _context.Manufacturers.SingleOrDefault(m => m.Id == Id);
            if(manufacturer == null)
            {
                return HttpNotFound();
            }
            return View(manufacturer);
        }
    }
}

FirstWebApp/FirstWebApp/Controllers/VineController.cs
using FirstWebApp.Models;
using FirstWebApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FirstWebApp.Controllers
{
    public class VineController : Controller
    {
        public ViewResult Index()
        {
            var vines = GetVines();
            return View(vines);
        }

        public ActionResult Details(int Id)
        {
            var vine = GetVines().SingleOrDefault(m => m.Id == Id);
            if (vine == null)
            {
                return HttpNotFound();
            }
            return View(vine);
        }

        private IEnumerable<Vine> GetVines()
        {
            return new List<Vine>
            {
                new Vine() { Id = 1, Name = "Bull's Heart" },
                new Vine() { Id = 2, Name = "New Love" }
            };
        }

        /// <summary>
        /// GET: Vine/Random
        /// </summary>
        /// <returns>Object of Movie view without needless casting</returns>
        public ActionResult Random()
        {
            var movie = new Movie() { Name = "Shreck" };
            var customers = new List<Customer>
            {
                new Customer { Name = "Customer 1"},
                new Customer { Name = "Customer 2"}
            };

            var viewModel = new RandomMovieViewModel
            {
                Movie = movie,
                Customers = customers
            };

            return View(viewModel);
        }

        /// <summary>
        /// Return content for vines/released/2014/03 and fails if year number has no 4 digits or month number has no 2 digits or is not in range of 1 - 12
        /// </summary>
        /// <param name="year">Year number must have 4 digits</param>
        /// <param name="month">Month number must have 2 digits and be in range of 1 - 12</param>
        /// <returns></returns>
        [Route("vine/released/{year:regex(\\d{4})}/{month:regex(\\d{2}):range(1,12)}")]
        public ActionResult ByReleaseDate(int year, int month)
        {
            ViewBag.Message = Content(year + "/" + month);
            return View();
        }

    }
}

FirstWebApp/FirstWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_NavigationBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year NuvoLetta, Inc</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FirstWebApp/FirstWebApp/Views/Shared/_NavigationBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("The taste of Life", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Vines", "Index", "Vine")</li>
                <li>@Html.ActionLink("Manufacturers", "Index", "Manufacturer")</li>
                <li>@Html.ActionLink("History", "Index", "History")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
            </ul>
        </div>
    </div>
</div>